# Generated by Django 3.2.9 on 2022-01-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',), 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
        migrations.AlterModelOptions(
            name='blogcomments',
            options={'ordering': ('-created_at',), 'verbose_name': 'BlogComment', 'verbose_name_plural': 'BlogComments'},
        ),
        migrations.AlterModelOptions(
            name='blogtags',
            options={'ordering': ('-created_at',), 'verbose_name': 'BlogTag', 'verbose_name_plural': 'BlogTags'},
        ),
        migrations.RemoveField(
            model_name='blogtags',
            name='updated_at',
        ),
    ]
