# Generated by Django 3.2.9 on 2022-01-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220111_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomments',
            options={'ordering': ('-created_at',), 'verbose_name': 'Blog Comment', 'verbose_name_plural': 'Blog Comments'},
        ),
        migrations.AlterModelOptions(
            name='blogtags',
            options={'ordering': ('-created_at',), 'verbose_name': 'Blog Tag', 'verbose_name_plural': 'Blog Tags'},
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/blog_post_photo'),
        ),
    ]
