# Generated by Django 3.2.9 on 2022-01-11 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0005_auto_20220111_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
