# Generated by Django 3.2.9 on 2022-01-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20220111_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtags',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
