# Generated by Django 3.2.9 on 2022-01-14 23:22

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='gallery/blog_post_photo'),
        ),
    ]
