# Generated by Django 3.2.9 on 2022-01-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/blog_post_photo'),
        ),
    ]
