# Generated by Django 3.2.9 on 2022-01-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20220124_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/blog_post_photo/'),
        ),
    ]
