# Generated by Django 3.2.9 on 2022-01-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20220131_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/blog_post_photo/%Y/%m/%d'),
        ),
    ]
