# Generated by Django 3.2.9 on 2022-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
